---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# econdata

<!-- badges: start -->
<!-- badges: end -->

The goal of econdata is to provide data from economics papers.

## Installation

``` r
# install.packages("devtools")
devtools::install_github("kvasilopoulos/econdata")
```

# Usage

```{r}
library(econdata)
# Stock and Watson (2001) dataset
sw2001
```

# List of papers' datasets

Dataset Name |  Description
-------------| -------------
sw2001       | Stock & Watson (2001). “Vector Autoregressions,”
bq1989       | Blanchard & Quah (1989) "The Dynamic Effects of Aggregate Demand and Supply Disturbances"
u2005        | Uhlig (2005) "What are the effects of monetary policy on output?"
psy2015      | Phillips, Shi & Yu (2015)

# List of miscellanious dataset 

Dataset Name |  Description
-------------| -------------
hprice       | Historical home prices
sp500        | Stock market data


---

Please note that the 'econdata' project is released with a
[Contributor Code of Conduct](.github/CODE_OF_CONDUCT.md).
By contributing to this project, you agree to abide by its terms.

